# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ethical Web Development
email: hello@adamdscott.com
description: > # this means to ignore newlines until "baseurl:"
  Ethical Web Development will be a series of short digital books that explore the ethics of practical development topics.
  The books will be released throughout 2016 and early 2017 as free downloads from O'Reilly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ethicalweb.org" # the base hostname & protocol for your site
twitter_username: adamdscott
github_username:  ascott1

# Build settings
markdown: kramdown

# ignores
exclude:
  - "node_modules"
  - "package.json"
  - "index.js"
  - npm-debug.log
  - README.md
  - LICENSE
